### ISSUE TITLE
Reporting of issues in POST with no parameters

### ISSUE THREAD

**Issue by Hipapheralkus** [ah8r/csrf#10]
When I perform Burp full active scan; I can see many POST requests without any parameters in either URL or body, which are reported as CSRF issues. Could you please implement checkbox "report issues with no parameters"? I know all of such requests are false positives in my context of the scan, so I would like not having them reported (as it is so for every single URL in my scope).

**Comment by ah8r** [comment]
@Hipapheralkus I've just committed an update (d34dcd38f6b129a5de846c1e1e8a1d38bf9f4c5e) which fixes this, among other things. The extension should now default to not reporting issues with no parameters, as in most cases I feel these would be false positives. The exception would be when apps are using REST-like URLs (which Burp treats like regular paths).

Can you test the new extension for me before I push to the BApp store? This should be the latest build: https://github.com/ah8r/csrf/blob/master/CSRFScanner.jar

**Comment by Hipapheralkus** [comment]
@ah8r thanks for a quick update. I removed all old reported issues; downloaded JAR file, imported in into Burp and ran the Passive analysis again. Unfortunately, I don't see any new checkbox (I'm unsure if there is supposed to be one) which I could click on (I made sure I downloaded the correct .jar file); but I still get numerous CSRF issues reported (which are generated by your extender). I also tried to reload the extender to be certain it gets unloaded and loaded again. Here is the sample of reported issue:
```
POST /dira/dirb/dir-c HTTP/1.1
Host: testedsite
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: fi-FI
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
Connection: close
Referer: https://testedsite
Content-Type: application/x-www-form-urlencoded
Content-Length: 0
Cookie: many_different_cookies


```

I don't see any output in Output log, but I see this in the error log:
```
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 1
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1072)
	at burp.jq.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by ah8r** [comment]
@Hipapheralkus can you confirm the version of Java you are running Burp with?

**Comment by Hipapheralkus** [comment]
@ah8r certainly:
```
C:\Users\hipapheralkus>java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by ah8r** [comment]
Thanks, I found the problem. It was a mixture of some poor coding on my part (or at least my misunderstanding of a Java function) and a failure of my git-fu as I hadn't actually committed the changes that I said I had!

Please can you download the latest master build and see if that works? It should have the new GUI options and hopefully won't generate that IndexOutOfBounds error.

**Comment by Hipapheralkus** [comment]
Thanks for a quick update. I've downloaded the newest version, reloaded the extender again, and see there is a checkbox "Report requests that contain no parameters" turned off by default. I left it as it was, deleted all the previous issues, ran passive scan again and I can still see over 1000 issues where POST without any parameters in body or URL is reported. On the pleasant side, there are no records in either "Output" nor "Errors". I would like to be more helpful... perhaps you could turn on some debugging output which I could share?

**Comment by ah8r** [comment]
@Hipapheralkus can you share a few of the requests with me? Feel free to redact any sensitive information, it's really the structure of the request I'm interested in and not the content. Can you also provide a copy of the actual issue text as well.

The relevant code line is: https://github.com/ah8r/csrf/blob/74fe69c716458d99142add0ee37375cfa253013b/BurpExtender.java#L1097

That if statement should only succeed if a user either has the "report requests with no parameters" checked, OR there are parameters found within the request. If you have the checkbox deselected, then the only reason you should be seeing these errors is if parameters are being found by Burp.

**Comment by ah8r** [comment]
OK, I think I've fixed this without the need to see your requests. I'm predicting that your requests had cookies. I forgot to remove them from the list of parameters that Burp provides, so they were being checked for CSRF tokens.

I've committed an update which should fix that, and hopefully now your requests should all work...but let me know if that is still an issue.

**Comment by Hipapheralkus** [comment]
I can now confirm it works and I only see issues which I wanted to see:)
Many thanks:)
